2024 HF1 description update
bmeviauac01/datadriven pull request #80
Opened 2024-08-15 06:59 UTC by AttilaHideg

2024-08-15 07:17 UTC, tibitoth approved these changes

2024-08-19 14:59 UTC, AttilaHideg commented
@tibitoth HF2 is bekerült

2024-08-21 18:37 UTC, tibitoth requested changes

2024-08-21 18:37 UTC, tibitoth commented on docs/hu/homework/ef/index.md
> +Ennek érdekében az Entity Framework egyik funkcióját érdemes kihasználni, a *QueryFilter*-t. Ennek a segítségével olyan szűrőfeltételeket határozhatunk meg, amiket globálisan, minden egyes lekérdezés
```suggestion
Ennek érdekében az Entity Framework egyik funkcióját érdemes kihasználni, a *Global Query Filter*-t. Ennek a segítségével olyan szűrőfeltételeket határozhatunk meg, amiket globálisan, minden egyes lekérdezésnél automatikusan alkalmaz az Entity Framework. 
```

2024-08-21 18:37 UTC, tibitoth commented on docs/hu/homework/ef/index.md
> +    A módosított C# forráskódot töltsd fel.
kérjünk PNG-t is a demonstrációról

2024-08-21 18:37 UTC, tibitoth commented on docs/hu/homework/ef/index.md
> +1. Az adatbázisból való törlés viselkedését változtasd meg arra, hogy az igazi törlés helyett csak átváltoztassa az `IsDeleted` változót!
Itt nekem nem tiszta, hogy mit várunk el. Kézi módosítást még a repository-ban + SaveChanges-t. Vagy maradjon a Remove a repóban és definiáljuk felül a SaveChanges-t?

2024-08-21 18:41 UTC, tibitoth commented
@AttilaHideg a megoldást is pusholtad a https://github.com/bmeviauac01/hazi-megoldas-ef repóba?

2024-08-23 14:36 UTC, tibitoth commented on docs/hu/homework/ef/index.md
> +    A módosított C# forráskódot töltsd fel.
mondjuk ezt nem tudom mivel lenne érdemes demonstrálni

2024-08-23 14:36 UTC, tibitoth commented on docs/hu/homework/ef/index.md
> +1. Az adatbázisból való törlés viselkedését változtasd meg arra, hogy az igazi törlés helyett csak átváltoztassa az `IsDeleted` változót!
pontosítottam

2024-08-23 14:36 UTC, tibitoth approved these changes

2024-08-23 14:36 UTC, merged